spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${adminname}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
