spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      static-path-pattern: /resources/**
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${adminname}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope:
              - email
              - profile
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}